export const TRANSACTION_TYPE_STATS_LOADING = 'TRANSACTION_TYPE_STATS_LOADING'
export const TRANSACTION_TYPE_STATS_ERROR = 'TRANSACTION_TYPE_STATS_ERROR'
export const TRANSACTION_TYPE_STATS_SUCCESS = 'TRANSACTION_TYPE_STATS_SUCCESS'
